version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    stop_grace_period: 1s
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/wordpress
    build:
      context: requirements/wordpress
    env_file: .env
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/wordpress
    build:
      context: requirements/nginx
    env_file: .env
    ports:
      - 443:443
    restart: always

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: $MOUNT_VOLUME_DIR/wordpress
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: $MOUNT_VOLUME_DIR/mariadb

networks:
  inception:
    driver: bridge
